name: CI
on: [push, pull_request]
env:
  ProjectName: Dawdler

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NET_TFM: net5.0
      Configuration: Release
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build .NET App
      shell: pwsh
      run: .\build.ps1

    - name: Upload .NET App
      continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ProjectName }}
        path: ${{ env.ProjectName }}/bin/${{ env.Configuration }}/${{ env.NET_TFM }}/publish/
