name: Docker
on:
  push:
    branches:
      - master
env:
  ProjectName: dawdler

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64
        push: true
        tags: ghcr.io/hmbsbige/${{ env.ProjectName }}:latest
